# Generated by Django 5.1.7 on 2025-04-18 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0002_alter_employee_salary"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="employee",
            table="employee_table",
        ),
    ]
